format = """
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$nodejs\
$rust\
$golang\
$php\
$time\
\n  """

[username]
style_user = "green bold"
style_root = "red bold"
format = "[$user]($style) "
disabled = false
show_always = true

[directory]
style = "fg:#e3e5e5"
format = "[$path]($style)"
truncation_length = 3
truncation_symbol = "…/"

[hostname]
ssh_only = false
format =  "on [$hostname](bold red) "
trim_at = ".companyname.com"
disabled = false

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
format = '[[ $symbol $branch](fg:#769ff0)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:#769ff0)]($style)'

[nodejs]
symbol = ""
format = '[[ $symbol ($version) ](fg:#769ff0)]($style)'

[rust]
symbol = ""
format = '[[ $symbol ($version) ](fg:#769ff0)]($style)'

[golang]
symbol = ""
format = '[[ $symbol ($version) ](fg:#769ff0)]($style)'

[php]
symbol = ""
format = '[[ $symbol ($version) ](fg:#769ff0i)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
format = '[[  $time ](fg:#a0a9cb)]($style)'
